; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:ControlLoop_LastRegeling_AdjustableBW]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200

lib_deps =
  thingpulse/ESP8266 and ESP32 OLED driver for SSD1306 displays@^4.6.2

build_flags = -D CONFIG_FREERTOS_GENERATE_RUN_TIME_STATS=1
			  -D CONFIG_FREERTOS_USE_STATS_FORMATTING_FUNCTIONS=1
			  -D CONFIG_FREERTOS_USE_TRACE_FACILITY=1
			  -D CONFIG_FREERTOS_VTASKLIST_INCLUDE_COREID=1
			  -D LED_PIN_ESP32_BOARD=2 ; pin number for blue LED on ESP32 board
			  -D INCLUDE_OLED_DISPLAY
